# IMPORTANT:
# Every field listed here must be added to the expandProps map in
# buildSrc/src/main/goovy/multiloader-common.gradle.

# Project
group=com.diontryban.sneak_through_berries
java_version=21

# Mod
mod_id=sneak_through_berries
mod_name=Sneak Through Berries
mod_author=Trikzon
version=21.0.1
license=LGPL-3.0-or-later
credits=
description=Sneak through Sweet Berry bushes without taking damage.

# Common
minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)
neoform_version=1.21-20240613.152323
parchment_minecraft_version=1.21
parchment_version=2024.11.10
ash_version=

# Fabric
fabric_version=0.102.0+1.21
fabric_loader_version=0.16.14
modmenu_version=11.0.3

# NeoForge
neoforge_version=21.0.167
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Dependencies
ars_version=5.2.1.757
ars_version_range=[5.0.0,)
curios_version=9.0.14+1.21.1
geckolib_version=4.6.6
jei_version=19.21.0.246